language: python 

python: 
  - "3.6"

services: 
  - postgresql

env: 
  -DJANGO=2.1.7 DB=postgresql

install: 
  - pip install -r requirements.txt

before_script: 
  - psql -c "CREATE DATABASE bit-trophy" -U postgres

script:
  - cd bit_trophy
  - python manage.py test