# Generated by Django 2.1.7 on 2019-03-13 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('platform', models.CharField(default='Add PC or Console', max_length=15)),
                ('genre', models.CharField(default='Add genre', max_length=25)),
                ('user_rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('is_playing', models.BooleanField(default=False)),
            ],
        ),
    ]
