# Generated by Django 2.2.1 on 2019-05-27 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the name of the game.', max_length=100)),
                ('platform', models.CharField(choices=[('PS4', 'PS4'), ('Xbox One', 'Xbox One'), ('Nintendo Switch', 'Nintendo Switch'), ('PC', 'PC'), ('Wii U', 'Wii U'), ('PS3', 'PS3'), ('Xbox 360', 'Xbox 360'), ('Wii', 'Wii'), ('Nintendo 3DS', 'Nintendo 3DS'), ('Playstation Vita', 'Playstation Vita'), ('Nintendo DS', 'Nintendo DS'), ('Playstation Portable', 'Playstation Portable'), ('PS2', 'PS2'), ('Xbox', 'Xbox'), ('Gamecube', 'Gamecube'), ('Gameboy Advance', 'Gameboy Advance'), ('Playstation', 'Playstation'), ('Nintendo 64', 'Nintendo 64'), ('Gameboy', 'Gameboy')], help_text='Select the console that you play the game on.', max_length=30)),
                ('genre', models.CharField(choices=[('Platformer', 'Platformer'), ('First-person shooter', 'First-person shooter'), ('Looter-shooter', 'Looter-shooter'), ('Fighting', 'Fighting'), ('Stealth', 'Stealth'), ('Survival', 'Survival'), ('Rhythm', 'Rhythm'), ('Survival horror', 'Survival horror'), ('Visual novel', 'Visual novel'), ('Adventure', 'Adventure'), ('Text adventure', 'Text adventure'), ('Role-playing game', 'Role-playing game'), ('Action RPG', 'Action RPG'), ('MMORPG', 'MMORPG'), ('Simulator', 'Simulator'), ('Strategy', 'Strategy'), ('Sports', 'Sports')], help_text='Select the game genre.', max_length=30)),
                ('user_rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('is_playing', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
