# Generated by Django 2.1.7 on 2019-03-14 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_videogame_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame',
            name='user',
        ),
        migrations.AlterField(
            model_name='videogame',
            name='user_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
