# Generated by Django 2.1.7 on 2019-03-15 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190314_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='user',
            field=models.ForeignKey(blank=True, default=999, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.User'),
        ),
    ]
