# Generated by Django 2.1.7 on 2019-03-17 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20190317_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='game.User'),
        ),
    ]
