# Generated by Django 2.1.7 on 2019-03-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20190320_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='genre',
            field=models.CharField(choices=[('Platformer', 'Platformer'), ('First-person shooter', 'First-person shooter'), ('Looter-shooter', 'Looter-shooter'), ('Fighting', 'Fighting'), ('Stealth', 'Stealth'), ('Survival', 'Survival'), ('Rhythm', 'Rhythm'), ('Survival horror', 'Survival horror'), ('Visual novel', 'Visual novel'), ('Adventure', 'Adventure'), ('Text adventure', 'Text adventure'), ('Role-playing game', 'Role-playing game'), ('Action RPG', 'Action RPG'), ('MMORPG', 'MMORPG'), ('Simulator', 'Simulator'), ('Strategy', 'Strategy'), ('Sports', 'Sports')], help_text='Select the game genre.', max_length=30),
        ),
    ]
